name 'sandinh-selinux'
version '0.1.3'

author 'giabao'
license 'Apache License, Version 2.0'
project_page 'https://sandinh.com'
source 'http://github.com/giabao/puppet-selinux'
summary 'This class manages SELinux on RHEL based systems.'
description 'This class manages SELinux on RHEL based systems.'
dependency 'puppetlabs/stdlib', '>=2.0.0'
